### ISSUE TITLE
I am loving it (no issue)

### ISSUE THREAD

**Issue by ghost** [JastinXyz/whatsactyl#1]
I am loving it
i hope it can be done 

you are the best for making this

**Comment by JastinXyz** [comment]
thank you for the support! I hope this repository helps you!

**Comment by ghost** [comment]
This helps me a lot

**Comment by ghost** [comment]
if you want i can help with it

**Comment by JastinXyz** [comment]
Of course, we are very grateful if anyone wants to contribute to this project

**Comment by ghost** [comment]
Is there a way that i can send you in prived?

**Comment by JastinXyz** [comment]
email me?

**Comment by ghost** [comment]
I am sorry for the late response 

My email is info@louisplayz.xyz btw

**Comment by sallllmanaall** [comment]
.map((v) => v.replace(/[^0-9]/g, "") + "@s.whatsapp.net")
        .includes(senderp.replace(":14", ""));

      //Auto Read
      if (conf.autoread) {
        whats.sendReadReceipt(from, msg.key.participant, [msg.key.id]);
      }

      //Function
      global.reply = async (iy) => {
        whats.sendMessage(msg.key.remoteJid, { text: iy }, { quoted: msg });
      };

      global.replyWithImgAndCap = async (link, cap) => {
        whats.sendMessage(
          msg.key.remoteJid,
          { image: { url: link }, caption: cap },
          { quoted: msg }
        );
      };

      global.error = async (info) => {
        whats.sendMessage(
          msg.key.remoteJid,
          { text: "❌ | Something error here, " + info },
          { quoted: msg }
        );
      };

      try {
        if (dy.startsWith(conf.prefix)) {
          args = dy.slice(conf.prefix.length).trim().split(/ +/g);
          command = args.shift().toLowerCase();
          sender = msg.pushName;
        } else {
          return;
        }
      } catch {}

      var afterArgs = args.slice(1).join(" ");
      if (availableCommands.has(command)) {
        if (fs.existsSync(`${__dirname}/commands/util/${command}.js`)) {
          require(`${__dirname}/commands/util/${command}.js`).run(
            whats,
            msg,
            args,
            q,
            text,
            afterArgs
          );
        } else if (
          fs.existsSync(`${__dirname}/commands/application/${command}.js`)
        ) {
          require(`${__dirname}/commands/application/${command}.js`).run(
            whats,
            msg,
            args,
            q,
            text,
            afterArgs
          );
        } else if (
          fs.existsSync(`${__dirname}/commands/client/${command}.js`)
        ) {
          require(`${__dirname}/commands/client/${command}.js`).run(
            whats,
            msg,
            args,
            q,
            text,
            afterArgs
          );
        } else if (fs.existsSync(`${__dirname}/commands/owner/${command}.js`)) {
          require(`${__dirname}/commands/owner/${command}.js`).run(
            whats,
            msg,
            args,
            q,
            text,
            afterArgs
          );
        }
      }
    } catch (e) {
      console.log(e);
    }
  });

  whats.ev.on("connection.update", async (update) => {
    const { connection, lastDisconnect } = update;
    if (connection === "close") {
      let reason = lastDisconnect.error
        ? new Boom(lastDisconnect)?.output.statusCode
        : 0;
      if (reason === DisconnectReason.badSession) {
        console.log(`Bad Session File, Please Delete Session and Scan Again`);
        startSock();
      } else if (reason === DisconnectReason.connectionClosed) {
        console.log("[WA SYSTEM] Connection closed, reconnecting....");
        startSock();
      } else if (reason === DisconnectReason.connectionLost) {
        console.log("[WA SYSTEM] Connection Lost from Server, reconnecting...");
        startSock();
      } else if (reason === DisconnectReason.connectionReplaced) {
        console.log(
          "[WA SYSTEM] Connection Replaced, Another New Session Opened, Please Close Current Session First"
        );
        process.exit();
      } else if (reason === DisconnectReason.loggedOut) {
        console.log(
          `[WA SYSTEM] Device Logged Out, Please Delete Session and Scan Again.`
        );
        process.exit();
      } else if (reason === DisconnectReason.restartRequired) {
        console.log("[WA SYSTEM] Restart Required, Restarting...");
        startSock();
      } else if (reason === DisconnectReason.timedOut) {
        console.log("[WA SYSTEM] Connection TimedOut, Reconnecting...");
        startSock();
      } else {
        console.log(`Unknown DisconnectReason: ${reason}|${connection}`);
      }
    }
    console.log("Connected!", update);
  });

  whats.ev.on("creds.update", saveState);
};

startSock();
